kmfs: Add support for app upgrade

diff --git a/meta-dstack/recipes-core/images/dstack-initramfs-files/kmfs-setup b/meta-dstack/recipes-core/images/dstack-initramfs-files/kmfs-setup
--- a/meta-dstack/recipes-core/images/dstack-initramfs-files/kmfs-setup
+++ b/meta-dstack/recipes-core/images/dstack-initramfs-files/kmfs-setup
@@ -27,14 +27,21 @@ fde_prepare() {
     fi
 
     rootfs_hash=$(jq -r .rootfs_hash ${CFG_FILE})
-    app_id=$(iohash sha256 -o! -t- -i ${APP_COMPOSE_FILE})
     kms_url=$(jq -r .kms_url ${CFG_FILE})
     ca_cert_hash=$(iohash sha256 -o! -t- -i ${CA_CERT})
+    upgraded_app_id=$(iohash sha256 -o! -t- -i ${APP_COMPOSE_FILE})
+    if [ -f "${HOST_SHARED}/.app_id" ]; then
+        app_id=$(cat ${HOST_SHARED}/.app_id)
+    else
+        app_id=${upgraded_app_id}
+    fi
 
     echo "FSINIT: Extending rootfs hash to RTMR, hash=${rootfs_hash}"
     tdxctl extend -i 3 --digest ${rootfs_hash} --associated-data "rootfs-hash" || panic "FSINIT: Failed to extend rootfs to RTMR"
     echo "FSINIT: Extending app id to RTMR, app_id=${app_id}"
     tdxctl extend -i 3 --digest ${app_id} --associated-data "app-id" || panic "FSINIT: Failed to extend app id to RTMR"
+    echo "FSINIT: Extending upgraded app id to RTMR, upgraded_app_id=${upgraded_app_id}"
+    tdxctl extend -i 3 --digest ${upgraded_app_id} --associated-data "upgraded-app-id" || panic "FSINIT: Failed to extend upgraded app id to RTMR"
     echo "FSINIT: Extending ca cert hash to RTMR, ca_cert_hash=${ca_cert_hash}"
     tdxctl extend -i 3 --digest ${ca_cert_hash} --associated-data "ca-cert-hash" || panic "FSINIT: Failed to extend ca cert hash to RTMR"
 
@@ -65,10 +72,16 @@ fde_prepare() {
         panic "FSINIT: Failed to get valid key phrase from KMS"
     fi
 
-    if [ -e ${HOST_SHARED}/initialized ]; then
+    if [ -e ${HOST_SHARED}/.bootstraped ]; then
         echo "[$(date +%H:%M:%S)] FSINIT: Mounting"
         echo "$key_phrase" | cryptsetup luksOpen --type luks2 -d- ${ROOT} rootfs_crypt || panic "FSINIT: Failed to open encrypted rootfs"
         mount /dev/mapper/rootfs_crypt /root || panic "FSINIT: Failed to mount rootfs"
+        if [ ! -e /root/.bootstraped ]; then
+            # Check if the rootfs has been properly bootstrapped by looking for the .bootstraped file
+            # This file is created at the end of the initial setup process
+            # If it doesn't exist, the rootfs was not properly initialized
+            panic "FSINIT: Encrypted rootfs is not bootstrapped"
+        fi
     else
         # Set up disk encryption and format the disk
 
@@ -116,7 +129,9 @@ fde_prepare() {
         fi
 
         cp -rT ${CFG_DIR} /root/tapp || panic "FSINIT: Failed to copy config to /root/tapp"
-        touch ${HOST_SHARED}/initialized || echo "FSINIT: Failed to touch initialized"
+        touch /root/.bootstraped || echo "FSINIT: Failed to touch bootstraped"
+        touch ${HOST_SHARED}/.bootstraped || echo "FSINIT: Failed to touch bootstraped"
+        echo ${app_id} > ${HOST_SHARED}/.app_id || echo "FSINIT: Failed to set app id"
     fi
 
     cp ${KMFS_WORK_DIR}/appkeys.json /root/tapp/appkeys.json || panic "FSINIT: Failed to copy appkeys.json to /root/tapp"
